import { assetPaths } from "@/assets";
import type { TournamentView } from "@/types/tournament";

export const demoTournaments: TournamentView[] = [
  {
    id: "demo-1",
    title: "National Softball Championship 2026",
    banner: assetPaths.banners.hero,
    organizer: "USA Softball Association",
    venue: "Riverside Sports Complex",
    city: "Austin",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    status: "active",
    tab: "present",
    prizePool: "$50,000",
    teams: 12,
    maxTeams: 16,
    registrationOpen: false,
    tournamentType: "Knockout",
    format: "knockout",
    liveMatches: [
      {
        id: "lm1",
        teamA: "Falcons",
        teamB: "Warriors",
        scoreA: "86/4",
        scoreB: "72/6",
        overs: "12.3",
        status: "live",
      },
    ],
    sponsors: ["SportsPro", "Elite Gear"],
  },
  {
    id: "demo-2",
    title: "Coastal League Finals",
    banner: assetPaths.tournament.defaultCover,
    organizer: "Coastal Sports Board",
    venue: "Harbor Field Stadium",
    city: "San Diego",
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    status: "active",
    tab: "present",
    prizePool: "$25,000",
    teams: 8,
    maxTeams: 8,
    registrationOpen: false,
    tournamentType: "League",
    format: "league",
    liveMatches: [
      {
        id: "lm2",
        teamA: "Storm",
        teamB: "Titans",
        scoreA: "54/2",
        scoreB: "48/5",
        overs: "9.1",
        status: "live",
      },
    ],
  },
  {
    id: "demo-3",
    title: "Spring Invitational 2026",
    banner: assetPaths.banners.hero,
    organizer: "Midwest Softball League",
    venue: "Grand Park Arena",
    city: "Chicago",
    startDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    endDate: new Date(Date.now() + 21 * 86400000).toISOString(),
    status: "upcoming",
    tab: "upcoming",
    prizePool: "$35,000",
    teams: 6,
    maxTeams: 12,
    registrationOpen: true,
    tournamentType: "Group Stage",
    format: "group_stage",
    liveMatches: [],
  },
  {
    id: "demo-4",
    title: "Youth Elite Cup",
    banner: assetPaths.tournament.defaultCover,
    organizer: "Junior Athletics Corp",
    venue: "Sunset Diamond Park",
    city: "Phoenix",
    startDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    endDate: new Date(Date.now() + 37 * 86400000).toISOString(),
    status: "upcoming",
    tab: "upcoming",
    prizePool: "$15,000",
    teams: 4,
    maxTeams: 10,
    registrationOpen: true,
    tournamentType: "League",
    format: "league",
    liveMatches: [],
  },
  {
    id: "demo-5",
    title: "Winter Classic 2025",
    banner: assetPaths.banners.hero,
    organizer: "National Softball Association",
    venue: "Metro Sports Center",
    city: "Denver",
    startDate: new Date(Date.now() - 60 * 86400000).toISOString(),
    endDate: new Date(Date.now() - 53 * 86400000).toISOString(),
    status: "completed",
    tab: "recent",
    prizePool: "$40,000",
    teams: 16,
    maxTeams: 16,
    winner: "Thunder Hawks",
    runnerUp: "Iron Eagles",
    mvp: "Sarah Mitchell",
    registrationOpen: false,
    tournamentType: "Knockout",
    format: "knockout",
    liveMatches: [],
    highlights: ["Final: Thunder Hawks 9–7 Iron Eagles", "Record attendance: 12,400"],
  },
  {
    id: "demo-6",
    title: "Pacific Rim Open",
    banner: assetPaths.tournament.defaultCover,
    organizer: "Pacific Sports Federation",
    venue: "Oceanview Stadium",
    city: "Seattle",
    startDate: new Date(Date.now() - 90 * 86400000).toISOString(),
    endDate: new Date(Date.now() - 83 * 86400000).toISOString(),
    status: "completed",
    tab: "recent",
    prizePool: "$28,000",
    teams: 10,
    maxTeams: 12,
    winner: "Pacific Storm",
    runnerUp: "Bay Lightning",
    mvp: "James Rivera",
    registrationOpen: false,
    tournamentType: "League",
    format: "league",
    liveMatches: [],
    highlights: ["MVP: 4 home runs in final week"],
  },
];
